create extension pgcrypto;

create table users(
  user_id int4 generated by default as identity primary key,
  username character varying(32) not null,
  password character varying(64) not null,
  joined_at timestamp with time zone default current_timestamp
);

create unique index username_idx on users (lower(username));